language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"

env:
  global:
    - GIT_NAME: "Raphiel Rollerscaperers"
    - GIT_EMAIL: raphielscape@outlook.com
    - GITHUB_REPO: RaphielGang/raphielgang.github.io
    - GIT_SOURCE: build
    - GIT_BRANCH: master

script:
- npm test
- npm install docpress && ./node_modules/.bin/docpress build

after_success:
  - |
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        npm install docpress git-update-ghpages
        ./node_modules/.bin/docpress build && ./node_modules/.bin/git-update-ghpages -e
      fi